### ISSUE TITLE
 an error when I use trace()

### ISSUE THREAD

**Issue by XinShengHUST** [nmoehrle/libcacc#2]
Dear nmoehrle,
   I used your gpu code in my texrecon project, and the bvh tree had been copied to the GPU successfully. But when I used the function trace(...) , there was a bug report: "CUDA error in ../elibs/rayint/libs/cacc/bvh_tree.h:78 (cudaFree(ptr)): an illegal memory access was encountered (77)" . Why cudaFree(prt) was used in the function trace()? I don't know how to fix this bug, and I hope that I can get your help.
  Thank you!

**Comment by nmoehrle** [comment]
Did you use the master or develop branch?

**Comment by XinShengHUST** [comment]
I used both branch and I get the same bug report.

**Comment by XinShengHUST** [comment]
I use trace() to test the visibility of a face in the view:
__global__ void test(cacc::BVHTree<cacc::DEVICE>::Data const bvh_tree,....){
          ...
         cacc::Vec3f view_pos;
         view_pos[0]=im_posx; 
         view_pos[1]=im_posy;
         view_pos[2]=im_posz;

         cacc::Ray bvh_ray;
         bvh_ray.origin=vert_center;
         bvh_ray.dir = view_pos - bvh_ray.origin;

         uint hit_face_id;
         cacc::tracing::trace( bvh_tree,bvh_ray, &hit_face_id);
}
The other functions in tracing.cu and bvh_tree.cu work well@nmoehrle

**Comment by XinShengHUST** [comment]
It turns out that I made a stupid mistake. I set the __global__ test() with <<<512,512>>>, while the TRACE_BLOCK_SIZE was set as 128. The bug report disappear when I use test<<<512,128>>> ().
Thank you for your help.

**Comment by nmoehrle** [comment]
When using the develop branch, which I would advise, you do not need to bind the textures anymore, sorry I forgot to remove that from the readme. However, you have to make sure that the short stack fits into your shared memory etc.

Cuda free is not called within trace, however, it is probably the first function that checks the cuda error state after the execution of your kernel so I assume the error is somewhere in the stack allocation.

**Comment by nmoehrle** [comment]
Ah I see, yes that has resulted in a wrong alignment of the short stacks in shared memory. Happy you figured it out :-)
I will add a note to the readme later today, I should have been more specific about this - sorry.

**Comment by XinShengHUST** [comment]
Thank you, nmoehrle, I really appreciate it for your kind help and great work. May you all the best.
